name: "Tests"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        
        
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: Key-v1-${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build tensor_parallel
        run: |
          pip install .[dev]
      - name: Test
        run: |
          cd tests
          pytest --durations=0 --durations-min=1.0 -v
